spring:
  jpa:
    show-slq: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enable: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/test
    username: Test
    password:
    driver-class-name: org.h2.Driver