spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:lab-base
        username: lab
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: true
